
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Tue Jun 28 01:18:29 CEST 2022
//----------------------------------------------------

package rs.ac.bg.etf.pp1;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int KOSACRTA = 23;
  public static final int PLUSPLUS = 34;
  public static final int DVOTACKA = 48;
  public static final int PROCENAT = 24;
  public static final int ZAREZ = 37;
  public static final int CONST = 6;
  public static final int charConst = 56;
  public static final int boolConst = 54;
  public static final int TACKAZAREZ = 36;
  public static final int CONTINUE = 16;
  public static final int VECEJEDNAKO = 28;
  public static final int JEDNAKOST = 25;
  public static final int MINUS = 21;
  public static final int AND = 31;
  public static final int RECORD = 17;
  public static final int PLUSPLUSPLUS = 50;
  public static final int OBICNA_ZAGRADA_L = 39;
  public static final int OR = 32;
  public static final int MANJEJEDNAKO = 30;
  public static final int CLASS = 4;
  public static final int UGLASTA_ZAGRADA_L = 41;
  public static final int PLUS = 20;
  public static final int OBICNA_ZAGRADA_D = 40;
  public static final int IF = 7;
  public static final int THIS = 47;
  public static final int DODELAVR = 33;
  public static final int UGLASTA_ZAGRADA_D = 42;
  public static final int TARABA = 18;
  public static final int EOF = 0;
  public static final int ident = 53;
  public static final int MINUSMINUS = 35;
  public static final int RETURN = 13;
  public static final int SUPER = 46;
  public static final int NEW = 10;
  public static final int error = 1;
  public static final int PROGRAM = 2;
  public static final int MAJMUNCE = 51;
  public static final int BREAK = 3;
  public static final int VITICASTA_ZAGRADA_L = 43;
  public static final int VOID = 14;
  public static final int NEJEDNAKOST = 26;
  public static final int VITICASTA_ZAGRADA_D = 44;
  public static final int MANJE = 29;
  public static final int ELSE = 5;
  public static final int VECE = 27;
  public static final int ENUM = 45;
  public static final int READ = 12;
  public static final int GOTO = 49;
  public static final int KAPICA = 52;
  public static final int FINAL = 19;
  public static final int WHILE = 9;
  public static final int TACKA = 38;
  public static final int EXTENDS = 15;
  public static final int PUTA = 22;
  public static final int numConst = 55;
  public static final int PRINT = 11;
  public static final int DO = 8;
}

